name: test

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '16 2 * * *'
  workflow_dispatch:

jobs:
  nvim-config:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # get tags/commits for good measure

      - name: Cache TS parsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/nvim/treesitter
          key: ${{ runner.os }}-ts-${{ hashFiles('lazy-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-ts-

      - name: Install luacheck (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y lua-check

      - name: Install luacheck (macOS)
        if: runner.os == 'macOS'
        run: brew install luacheck

      # ─────────────────────────────────────────────────────────────
      # 1 · Online phase – download & bootstrap the tool-chain
      # ─────────────────────────────────────────────────────────────
      - name: Bootstrap (online)
        run: make offline

      # ─────────────────────────────────────────────────────────────
      # 2 · Offline phase – verify the repo works without network
      # ─────────────────────────────────────────────────────────────
      - name: Smoke test (offline, no plugins)
        run: make smoke
        env:
          OFFLINE: 1          # skip downloads
          NVIM_OFFLINE_BOOT: 1  # skip plugin load

      - name: Head-less full test (offline, plugins enabled)
        run: make test
        env:
          OFFLINE: 1          # skip downloads

      - name: Lint (offline)
        run: make lint
        env:
          OFFLINE: 1

  nightly:
    needs: nvim-config
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      NVIM_VERSION: nightly
    steps:
      - uses: actions/checkout@v4
      - name: Cache TS parsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/nvim/treesitter
          key: ${{ runner.os }}-ts-${{ hashFiles('lazy-lock.json') }}
          restore-keys: ${{ runner.os }}-ts-
      - name: Bootstrap & offline tests (nightly)
        run: |
          make offline
          OFFLINE=1 make smoke
          OFFLINE=1 make test

